sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t changrae/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true changrae/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: Dockerreactapp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-527137765047
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY  
